package org.espe.sigec.web.utils;

public interface SigecConstantes {
	Integer MINIMO_ESTUDIANTES = 12;
	Integer MAXIMO_ESTUDIANTES = 30;
	String TIPO_CURSO_CORPORATIVO = "CORP";
	String TIPO_CURSO_INDIVIDUAL = "IND";
	String ESTADO_ACTIVO_BOOLEANO = "1";
	String ESTADO_INACTIVO_BOOLEANO = "0";
	
	String PERFIL_PROFESOR = "PRO";
	String PERFIL_ADMINISTRATIVO= "ADM";
	String PERFIL_ESTUDIANTE = "EST";
	String PERFIL_INVITADO = "INV";
	String CATALOGO_COSTOS_GASTOS = "CYG";
	String CATALOGO_DETALLE_MANUALES = "MAN";
	String CATALOGO_DETALLE_REFRIGERIOS = "REF";
	String ESTADO_PAGADO = "PAGADO";
	String ESTADO_POR_PAGAR = "DEBE";
}
